openapi: 3.0.0
info:
  title: Bank Argent API documentation
  description: Proposes new API endpoints methodologies for enhanced user profile management and related functionalities.
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
servers:
  - url: http://localhost:3001/api/v1
paths:
  
  /user/profile/transactions:
    get:
      security:
        - bearerAuth: []
      tags:
        - User Module Transaction
      summary: Grouped User Transactions API
      description: Get all transactions for the current month, grouped by type or category.
      parameters:
        - in: header
          name: securitySchemes
          description: Attach Bearer JWT token
          required: true
          schema:
            type: string
        - in: query
          name: month
          schema:
            type: string
            format: date
          description: "Month for which transactions are to be fetched. Format: YYYY-MM. If not specified, current month is used."
          required: false
      responses:
        '200':
          description: User transactions retrieved and grouped successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  transactions:
                    type: array
                    items:
                      $ref: '#/components/schemas/GroupedTransaction'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized Le token JWT is not provided or is invalid
        '403':
          description: Forbidden. User does not have permission to access this transaction
        
        '500':
          description: Internal Server Error

  /user/profile/transactions/{id}:
    get:
      security:
        - bearerAuth: []
      tags:
        - User Module Transaction
      summary: User Transaction API
      description: Fetches details of a specific user transaction identified by its ID
      parameters:
        - in: header
          name: securitySchemes
          description: Attach Bearer JWT token
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 'ID of the transaction to fetch'
      responses:
        '200':
          description: User Transaction retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '400':
          description: Invalid Fields
        '401':
          description: Unauthorized Le token JWT is not provided or is invalid
        '403':
          description: Forbidden. User does not have permission to access this transaction
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      security:
        - bearerAuth: []
      tags:
        - User Module Transaction
      summary: User Transaction API
      description: Updates the notes for a specific user transaction identified by its ID
      parameters:
        - in: header
          name: securitySchemes
          description: Attach Bearer JWT token
          required: true
          schema:
            type: string
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: 'ID of one transaction to update'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionUpdate'
      responses:
        '200':
          description: User Transaction updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'

        '400':
          description: Invalid Fields
        '401': 
          description: Unauthorized Le token JWT is not provided or is invalid
        '403':
          description: Forbidden. User does not have permission to update this
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ApiResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
    GroupedTransaction:
      type: object
      properties:
        transaction:
          type: array
          items:
            $ref: '#/components/schemas/Transaction'
    Transaction:
      type: object
      properties:
        id:
          type: string
        transactionData:
          type: object
          properties:
            date:
              type: string
            description:
              type: string
            amount:
              type: number
            detail:
              type: object
              properties:
                typeoftransaction:
                  type: string
                category:
                  type: string
                notes:
                  type: string
    TransactionUpdate:
      type: object
      properties:
        category:
          type: string
        notes:
          type: string
